// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nivra.Api.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nivra.Api.Infrastructure.Migrations
{
    [DbContext(typeof(NivraDbContext))]
    partial class NivraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nivra.Api.Domain.AdCampaign", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClickUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Region")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "StartsAt", "EndsAt");

                    b.ToTable("ad_campaigns", "public");

                    b.HasData(
                        new
                        {
                            Id = "ad_nivra_launch",
                            Body = "Mas boveda cifrada y mas dispositivos cuando quieras crecer.",
                            ClickUrl = "https://nivra.app/premium",
                            EndsAt = new DateTimeOffset(new DateTime(2036, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Locale = "es",
                            Placement = "vault_home",
                            StartsAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Nivra Premium"
                        });
                });

            modelBuilder.Entity("Nivra.Api.Domain.AdImpressionAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Placement", "Day")
                        .IsUnique();

                    b.ToTable("ad_impressions", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.CallSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ParticipantUserIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("participant_user_ids");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("InitiatorUserId", "StartedAt");

                    b.ToTable("calls", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.ContactRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ContactUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NicknameCiphertext")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ContactUserId");

                    b.HasIndex("OwnerUserId", "ContactUserId")
                        .IsUnique();

                    b.ToTable("contacts", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.FriendRequestRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId", "Status");

                    b.HasIndex("FromUserId", "ToUserId", "Status");

                    b.ToTable("friend_requests", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.ConversationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TitleCiphertext")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastMessageAt");

                    b.ToTable("conversations", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.DeviceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("devices", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.FileObject", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AllowedUserIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_user_ids");

                    b.Property<string>("ClientSha256")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EncryptedSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeTypeCiphertext")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultRoomId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("VaultRoomId");

                    b.ToTable("files", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.MessageEnvelope", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("DeleteAfterRead")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptedPolicy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SenderDeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ServerReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SenderDeviceId");

                    b.HasIndex("ConversationId", "ServerReceivedAt");

                    b.HasIndex("SenderUserId", "ClientMessageId")
                        .IsUnique();

                    b.ToTable("messages", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.PlanEntitlements", b =>
                {
                    b.Property<bool>("AdsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("EncryptedBackupsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxGroupParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLinkedDevices")
                        .HasColumnType("integer");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProfessionalSpacesEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("VaultStorageBytes")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Nivra.Api.Domain.PushTokenRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenCiphertext")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "DeviceId", "RevokedAt");

                    b.ToTable("push_tokens", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.SecurityAuditEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("security_audit_events", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.SessionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("DeviceId", "RevokedAt");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("sessions", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.StoryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AllowedUserIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_user_ids");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaFileObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ViewedByUserIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("viewed_by_user_ids");

                    b.Property<bool>("ViewOnce")
                        .HasColumnType("boolean");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("MediaFileObjectId");

                    b.HasIndex("OwnerUserId", "CreatedAt");

                    b.HasIndex("Visibility", "ExpiresAt");

                    b.ToTable("stories", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDiscoverable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("free");

                    b.Property<string>("ProfilePhotoDataUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("DisabledAt");

                    b.HasIndex("IsDiscoverable");

                    b.HasIndex("Phone");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.VaultItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedMetadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FileObjectId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId", "DeletedAt");

                    b.ToTable("vault_items", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.VaultRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedWelcome")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RetentionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OwnerUserId", "ClosedAt");

                    b.ToTable("vault_rooms", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.VaultRoomMember", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VaultRoomId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("VaultRoomId", "UserId")
                        .IsUnique();

                    b.ToTable("vault_room_members", "public");
                });

            modelBuilder.Entity("Nivra.Api.Domain.AdImpressionAggregate", b =>
                {
                    b.HasOne("Nivra.Api.Domain.AdCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.CallSession", b =>
                {
                    b.HasOne("Nivra.Api.Domain.ConversationRecord", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.ContactRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ContactUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.FriendRequestRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.ConversationRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nivra.Api.Domain.PrivacySettings", "PrivacySettings", b1 =>
                        {
                            b1.Property<string>("ConversationRecordId")
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("AllowForwarding")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_allow_forwarding");

                            b1.Property<bool>("AllowScreenshots")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_allow_screenshots");

                            b1.Property<int?>("DefaultMessageTtlSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("privacy_default_message_ttl_seconds");

                            b1.Property<bool>("HideNotificationContent")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_hide_notification_content");

                            b1.Property<string>("PrivacyPreset")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("privacy_preset");

                            b1.Property<bool>("ReadReceipts")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_read_receipts");

                            b1.HasKey("ConversationRecordId");

                            b1.ToTable("conversations", "public");

                            b1.WithOwner()
                                .HasForeignKey("ConversationRecordId");
                        });

                    b.OwnsMany("Nivra.Api.Domain.ConversationParticipant", "Participants", b1 =>
                        {
                            b1.Property<string>("conversation_id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("UserId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("user_id");

                            b1.Property<bool>("CanChangePrivacy")
                                .HasColumnType("boolean")
                                .HasColumnName("can_change_privacy");

                            b1.Property<bool>("CanInvite")
                                .HasColumnType("boolean")
                                .HasColumnName("can_invite");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<DateTimeOffset?>("RemovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removed_at");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("role");

                            b1.HasKey("conversation_id", "UserId");

                            b1.HasIndex("UserId", "RemovedAt");

                            b1.ToTable("conversation_participants", "public");

                            b1.WithOwner()
                                .HasForeignKey("conversation_id");
                        });

                    b.Navigation("Participants");

                    b.Navigation("PrivacySettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.DeviceRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nivra.Api.Domain.KeyBundle", "KeyBundle", b1 =>
                        {
                            b1.Property<string>("DeviceRecordId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("IdentityKey")
                                .HasColumnType("text")
                                .HasColumnName("identity_key");

                            b1.Property<DateTimeOffset>("LastRotatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("keys_last_rotated_at");

                            b1.Property<string>("OneTimePreKeys")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("one_time_pre_keys");

                            b1.Property<string>("PreKeySignature")
                                .HasColumnType("text")
                                .HasColumnName("pre_key_signature");

                            b1.Property<string>("SignedPreKey")
                                .HasColumnType("text")
                                .HasColumnName("signed_pre_key");

                            b1.HasKey("DeviceRecordId");

                            b1.ToTable("devices", "public");

                            b1.WithOwner()
                                .HasForeignKey("DeviceRecordId");
                        });

                    b.Navigation("KeyBundle")
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.FileObject", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.VaultRoom", null)
                        .WithMany()
                        .HasForeignKey("VaultRoomId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Nivra.Api.Domain.MessageEnvelope", b =>
                {
                    b.HasOne("Nivra.Api.Domain.ConversationRecord", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("SenderDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Nivra.Api.Domain.DeliveryReceipt", "Receipts", b1 =>
                        {
                            b1.Property<string>("message_id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("UserId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("user_id");

                            b1.Property<string>("DeviceId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("device_id");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_at");

                            b1.Property<DateTimeOffset?>("DeliveredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivered_at");

                            b1.Property<DateTimeOffset?>("ReadAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("read_at");

                            b1.HasKey("message_id", "UserId", "DeviceId");

                            b1.HasIndex("UserId", "DeviceId", "DeletedAt");

                            b1.ToTable("message_receipts", "public");

                            b1.WithOwner()
                                .HasForeignKey("message_id");
                        });

                    b.OwnsMany("Nivra.Api.Domain.RecipientCiphertext", "Recipients", b1 =>
                        {
                            b1.Property<string>("message_id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("UserId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("user_id");

                            b1.Property<string>("DeviceId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("device_id");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ciphertext");

                            b1.Property<string>("FileObjectId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("file_object_id");

                            b1.Property<string>("Header")
                                .HasColumnType("text")
                                .HasColumnName("header");

                            b1.HasKey("message_id", "UserId", "DeviceId");

                            b1.HasIndex("FileObjectId");

                            b1.HasIndex("UserId", "DeviceId");

                            b1.ToTable("message_recipients", "public");

                            b1.WithOwner()
                                .HasForeignKey("message_id");
                        });

                    b.Navigation("Receipts");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Nivra.Api.Domain.PushTokenRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.SecurityAuditEvent", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Nivra.Api.Domain.SessionRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.DeviceRecord", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.StoryRecord", b =>
                {
                    b.HasOne("Nivra.Api.Domain.FileObject", null)
                        .WithMany()
                        .HasForeignKey("MediaFileObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.UserAccount", b =>
                {
                    b.OwnsOne("Nivra.Api.Domain.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<string>("UserAccountId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("password_algorithm");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("password_hash");

                            b1.Property<int>("Iterations")
                                .HasColumnType("integer")
                                .HasColumnName("password_iterations");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("password_salt");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Nivra.Api.Domain.PrivacySettings", "PrivacySettings", b1 =>
                        {
                            b1.Property<string>("UserAccountId")
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("AllowForwarding")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_allow_forwarding");

                            b1.Property<bool>("AllowScreenshots")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_allow_screenshots");

                            b1.Property<int?>("DefaultMessageTtlSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("privacy_default_message_ttl_seconds");

                            b1.Property<bool>("HideNotificationContent")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_hide_notification_content");

                            b1.Property<string>("PrivacyPreset")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("privacy_preset");

                            b1.Property<bool>("ReadReceipts")
                                .HasColumnType("boolean")
                                .HasColumnName("privacy_read_receipts");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("users", "public");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("PrivacySettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.VaultItem", b =>
                {
                    b.HasOne("Nivra.Api.Domain.FileObject", null)
                        .WithMany()
                        .HasForeignKey("FileObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nivra.Api.Domain.VaultRoom", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nivra.Api.Domain.PasswordHash", "PinHash", b1 =>
                        {
                            b1.Property<string>("VaultRoomId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Algorithm")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pin_algorithm");

                            b1.Property<string>("Hash")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("pin_hash");

                            b1.Property<int?>("Iterations")
                                .HasColumnType("integer")
                                .HasColumnName("pin_iterations");

                            b1.Property<string>("Salt")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("pin_salt");

                            b1.HasKey("VaultRoomId");

                            b1.ToTable("vault_rooms", "public");

                            b1.WithOwner()
                                .HasForeignKey("VaultRoomId");
                        });

                    b.Navigation("PinHash");
                });

            modelBuilder.Entity("Nivra.Api.Domain.VaultRoomMember", b =>
                {
                    b.HasOne("Nivra.Api.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nivra.Api.Domain.VaultRoom", null)
                        .WithMany()
                        .HasForeignKey("VaultRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
