using System.Reflection;
using System.Text.Json;
using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nivra.Api.Domain;
using Nivra.Api.Endpoints;
using Nivra.Api.Infrastructure;
using Nivra.Api.Services;
using Nivra.Api.Contracts;

var count = 0;
void Check(bool condition, string label) { if (!condition) throw new Exception(label); Console.WriteLine($"PASS {label}"); count++; }
bool Allowed(HistoryKeyTransfer request, DeviceRecord? source, DeviceRecord? target, DateTimeOffset now) => (bool)typeof(EndpointExtensions).GetMethod("HistoryTransferAllowed", BindingFlags.NonPublic | BindingFlags.Static)!.Invoke(null, [request, source, target, now])!;
bool Envelope(SealedHistoryKeyResponse body, string sourceKey) => (bool)typeof(EndpointExtensions).GetMethod("ValidHistoryTransferEnvelope", BindingFlags.NonPublic | BindingFlags.Static)!.Invoke(null, [body, sourceKey])!;
string B64Url(byte[] bytes) => Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');
using var pair = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
var point = pair.ExportParameters(false);
var key = JsonSerializer.Serialize(new { kty = "EC", crv = "P-256", x = B64Url(point.Q.X!), y = B64Url(point.Q.Y!) });
var now = DateTimeOffset.UtcNow;
DeviceRecord Device(string id, string user = "alice") => new() { Id = id, Name = "Test", UserId = user, IsTrusted = true, KeyBundle = new KeyBundle { IdentityKey = key } };
var source = Device("source"); var target = Device("target");
var request = new HistoryKeyTransfer { Id = "request", UserId = "alice", TargetDeviceId = "target", TargetIdentityKey = key, CreatedAt = now, ExpiresAt = now.AddMinutes(15) };
Check(Allowed(request, source, target, now), "authorized same-account active devices can transfer");
Check(!Allowed(request, Device("source", "mallory"), target, now), "cross-account source cannot transfer another user's keyring");
Check(!Allowed(request, source, Device("target", "mallory"), now), "cross-account target is rejected");
Check(!Allowed(request, source, Device("different"), now), "target device is bound to request");
Check(!Allowed(request, target, target, now), "target cannot submit a source response to itself");
Check(!Allowed(request, null, target, now) && !Allowed(request, source, null, now), "missing devices are rejected");
source.RevokedAt = now; Check(!Allowed(request, source, target, now), "revoked source is rejected even with a cached JWT"); source.RevokedAt = null;
target.RevokedAt = now; Check(!Allowed(request, source, target, now), "revoked target cannot receive old ciphertext"); target.RevokedAt = null;
source.IsTrusted = false; Check(!Allowed(request, source, target, now), "untrusted source is rejected"); source.IsTrusted = true;
target.IsTrusted = false; Check(!Allowed(request, source, target, now), "untrusted target is rejected"); target.IsTrusted = true;
Check(!Allowed(request, source, target, request.ExpiresAt), "expiry boundary rejects replay");
target.KeyBundle.IdentityKey = key + " "; Check(!Allowed(request, source, target, now), "target key rotation invalidates original request"); target.KeyBundle.IdentityKey = key;
var header = JsonSerializer.Serialize(new { v = 1, alg = "ECDH-P256-A256GCM", senderPublicKey = JsonSerializer.Deserialize<JsonElement>(key), iv = Convert.ToBase64String(new byte[12]) });
var valid = new SealedHistoryKeyResponse(header, Convert.ToBase64String(new byte[32]));
Check(Envelope(valid, key), "opaque authenticated ciphertext accepts bound source public key");
Check(!Envelope(valid with { Ciphertext = "plaintext" }, key), "plain text is not a transferable ciphertext");
Check(!Envelope(valid with { Ciphertext = Convert.ToBase64String(new byte[15]) }, key), "ciphertext without GCM tag is rejected");
Check(!Envelope(valid with { Header = "{}" }, key), "missing source metadata is rejected");
Check(!Envelope(valid with { Header = header.Replace("ECDH-P256-A256GCM", "none") }, key), "wrong algorithm is rejected");
Check(!Envelope(valid with { Header = header.Replace("\"v\":1", "\"v\":9") }, key), "unsupported envelope version is rejected");
Check(!Envelope(valid with { Ciphertext = new string('A', 512 * 1024 + 1) }, key), "oversized keyring ciphertext is rejected");
using var different = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
var other = different.ExportParameters(false);
var differentKey = JsonSerializer.Serialize(new { kty = "EC", crv = "P-256", x = B64Url(other.Q.X!), y = B64Url(other.Q.Y!) });
Check(!Envelope(valid, differentKey), "claimed source cannot substitute another device public key");
source.KeyBundle.IdentityKey = JsonSerializer.Serialize(new { kty = "EC", crv = "P-256", x = B64Url(point.Q.X!), y = B64Url(point.Q.Y!), d = "must-not-be-published" });
Check(!Allowed(request, source, target, now), "server key directory never accepts a private key as public metadata");
source.KeyBundle.IdentityKey = JsonSerializer.Serialize(new { kty = "EC", crv = "P-256", x = new string('!', 43), y = B64Url(point.Q.Y!) });
Check(!Allowed(request, source, target, now), "invalid coordinate encodings cannot authorize a history recipient");
source.KeyBundle.IdentityKey = JsonSerializer.Serialize(new { kty = "EC", crv = "P-256", x = B64Url(new byte[32]), y = B64Url(new byte[32]) });
Check(!Allowed(request, source, target, now), "coordinates outside the P-256 curve are rejected");
var sourceBundle = new KeyBundle { IdentityKey = key };
var localBundle = new KeyBundleRequest(differentKey, differentKey, "webcrypto-p256", []);
var localChallenge = new QrLoginChallenge("qr", "123456", "Destination", localBundle, null, "new-hardware", now, now.AddMinutes(1));
var selectQrBundle = typeof(EndpointExtensions).GetMethod("QrTargetKeyBundle", BindingFlags.NonPublic | BindingFlags.Static)!;
Check(ReferenceEquals(selectQrBundle.Invoke(null, [localChallenge, new DeviceRecord { Id = "source", Name = "Source", UserId = "alice", KeyBundle = sourceBundle }]), localBundle), "QR registers the locally generated destination identity without adopting the source key");
var legacyChallenge = new QrLoginChallenge("legacy", "123456", "Old destination", null, null, "old-hardware", now, now.AddMinutes(1));
Check(((KeyBundleRequest)selectQrBundle.Invoke(null, [legacyChallenge, new DeviceRecord { Id = "source", Name = "Source", UserId = "alice", KeyBundle = sourceBundle }])!).IdentityKey == key, "old QR destinations retain compatibility without changing the source identity");
var options = new DbContextOptionsBuilder<NivraDbContext>().UseNpgsql("Host=localhost;Database=unused;Username=unused;Password=unused").Options;
using var db = new NivraDbContext(options);
var migrations = db.GetService<IMigrationsAssembly>();
Check(migrations.Migrations.Keys.Any(x => x.EndsWith("HistoryKeyTransfers")), "history transfer migration is discoverable on API startup");
var transferModel = db.Model.FindEntityType(typeof(HistoryKeyTransfer))!;
Check(transferModel.GetProperties().All(x => !x.Name.Contains("Private", StringComparison.OrdinalIgnoreCase)), "database request schema contains no private key material");
Check(db.Model.FindEntityType(typeof(HistoryKeyTransferResponse))!.GetForeignKeys().Single().DeleteBehavior == DeleteBehavior.Cascade, "expired requests cascade their sealed responses");
Console.WriteLine($"Completed {count} history-security checks.");
